site_name: Documentación de administración de NFMS4REDD
theme: 'material'
markdown_extensions: [codehilite]
pages:
- 'Introducción': index.md
- 'Inventario': inventory.md
- 'Instalación del servidor':
    - 'Instalación con Docker': install/docker.md
    - 'Instalación con paquetes': install/packages.md
    - 'Copias de seguridad': install/backups.md
    - 'Rendimiento': install/performance.md
- 'Carga de datos en PostGIS': postgis.md
- 'Publicación de datos en GeoServer': geoserver.md
- 'Configuración del portal':
    - 'Configuración del portal': config/portal.md
    - 'Configuración de capas temporales': config/temporal.md
    - 'Configuración de capas raster temporales': config/raster_temporal.md
- 'Optimizaciones': optimization.md

